export const CONVERSATION_DOCUMENT_KIND = "agentforge.conversation" as const;
export const CONVERSATION_DOCUMENT_VERSION_1 = 1 as const;
export const CONVERSATION_DOCUMENT_VERSION_2 = 2 as const;
export const CONVERSATION_DOCUMENT_VERSION = CONVERSATION_DOCUMENT_VERSION_2;

export const CONVERSATION_STORE_ENTRY_DOCUMENT_KIND =
  "agentforge.conversation-store-entry" as const;
export const CONVERSATION_STORE_ENTRY_DOCUMENT_VERSION_1 = 1 as const;
export const CONVERSATION_STORE_ENTRY_DOCUMENT_VERSION_2 = 2 as const;
export const CONVERSATION_STORE_ENTRY_DOCUMENT_VERSION =
  CONVERSATION_STORE_ENTRY_DOCUMENT_VERSION_2;
